# Generated by Django 5.2 on 2025-04-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("birth", models.CharField(max_length=100)),
                ("condition_icon", models.CharField(blank=True, max_length=10)),
                ("condition_details", models.CharField(blank=True, max_length=200)),
                ("address", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
